-- apply_capture_proposal: normalise the task vocabulary before writing.
-- Applied to the live project 2026-08-17.
--
-- The extraction pass proposes tasks with status 'todo' and priority 'Normal'.
-- This database allows status open|doing|done|dropped|waiting and priority
-- High|Med|Low, so every task proposal would have failed its check constraint
-- on Accept — and a task proposal is the one kind EVERY document produces.
--
-- Normalising here rather than only in the extractor is deliberate: this
-- function is the seam between a model's opinion and a real table, and the
-- only place guaranteed to run for every proposal whatever produced it.
-- Unknown values are left alone so the constraint still fails loudly rather
-- than being silently coerced to a default.
--
-- The full function body is the one live on the project; see
-- `select pg_get_functiondef(...)`. Only the v_payload normalisation block and
-- the switch from v_prop.payload to v_payload differ from the original.
