-- 20260811222457_meals.sql
-- THE BRAIN — the food module.
--
-- ALREADY APPLIED to the live project (qttroyuajpyelfrbxzzt) on 11 Aug 2026.
-- This file is the RECORD, not an instruction. Do not re-run it against the
-- live database: the schema would fail on the existing tables and, if the
-- CREATEs were skipped, the inserts would duplicate all fifty meals.
--
-- Nutrition & Recovery's standard is "eat and sleep like someone with plans",
-- and Training is the keystone habit, so meals carry protein first.
--
-- Two honesty rules:
--   · protein_g and kcal are ESTIMATES per serving. `estimates` defaults true
--     and only flips when a measured figure replaces a guess.
--   · image_source and image_licence are stored per row from day one. Costs
--     nothing now; saves a rebuild if this ever stops being private.
--
-- Images and titles: TheMealDB, whose terms expressly permit copying and
-- storing content from the official endpoints. Method text written fresh:
-- recipe steps and ingredient lists are not copyrightable (Publications
-- Int'l v. Meredith, 7th Cir. 1996; same outcome in the UK via the
-- originality test) but photographs are, which is why the image source
-- matters and the text source does not.

create table meals (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null default auth.uid(),
  name          text not null,
  slug          text not null,
  category      text not null,
  cuisine       text,
  image_url     text,
  image_source  text,
  image_licence text,
  servings      int  not null default 2,
  prep_min      int,
  cook_min      int,
  protein_g     int,
  kcal          int,
  estimates     boolean not null default true,
  tags          text[] not null default '{}',
  method        text[] not null default '{}',
  notes         text,
  favourite     boolean not null default false,
  last_cooked_on date,
  times_cooked  int not null default 0,
  created_at    timestamptz not null default now(),
  meta          jsonb not null default '{}',
  unique (user_id, slug)
);

create table meal_ingredients (
  id         uuid primary key default gen_random_uuid(),
  meal_id    uuid not null references meals on delete cascade,
  user_id    uuid not null default auth.uid(),
  item       text not null,
  qty        numeric,
  unit       text,
  sort_order int not null default 0,
  optional   boolean not null default false
);

alter table meals enable row level security;
alter table meal_ingredients enable row level security;

create policy "own rows" on meals for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own rows" on meal_ingredients for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

create index meals_by_protein on meals (user_id, protein_g desc);
create index meals_by_time on meals (user_id, ((coalesce(prep_min,0) + coalesce(cook_min,0))));
create index meal_ingredients_by_meal on meal_ingredients (meal_id, sort_order);

comment on column meals.protein_g is
  'Grams per serving. ESTIMATE while meals.estimates is true - never presented as measured.';

-- ------------------------------------------------------------------
-- The fifty. No beef in any recipe, verified against the ingredient
-- rows rather than the category label.
-- ------------------------------------------------------------------

with m as (
insert into meals (user_id, name, slug, category, cuisine, image_url, image_source, image_licence,
                   servings, prep_min, cook_min, protein_g, kcal, tags, method) values
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Adana Kebab','adana-kebab','lamb','Turkish','https://www.themealdb.com/images/media/meals/04axct1763793018.jpg','themealdb','see themealdb terms',4,20,15,38,520,'{"high-protein","barbecue"}','{"Use lamb mince with real fat in it, around 20 per cent. Lean mince makes dry kebabs.","Mix with grated onion squeezed dry, red pepper paste, chilli flakes and salt. Knead for 5 minutes until sticky.","Rest the mix in the fridge an hour, then press onto flat skewers with wet hands.","Grill over high heat 6-7 minutes, turning once. Serve on flatbread with sumac onions and grilled peppers."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Spicy Arrabbiata Penne','arrabbiata-penne','pasta','Italian','https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg','themealdb','see themealdb terms',2,5,20,15,480,'{"quick","cheap","vegetarian","storecupboard"}','{"Warm garlic and dried chilli in olive oil until the garlic is pale gold, no further.","Add the tomatoes, crush them with a spoon, season, and simmer 15 minutes.","Cook the penne one minute short of the packet time.","Finish the pasta in the sauce with a splash of its water. Parsley and olive oil off the heat."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Baked Salmon with Fennel and Tomatoes','baked-salmon-fennel','seafood','Mediterranean','https://www.themealdb.com/images/media/meals/1548772327.jpg','themealdb','see themealdb terms',2,10,25,38,420,'{"one-tray","low-carb","high-protein"}','{"Slice the fennel thin, toss with tomatoes, oil, lemon zest and salt.","Roast at 200C for 15 minutes so the fennel starts to soften.","Sit the salmon on top, season, add the lemon slices.","Back in for 10-12 minutes. The salmon is done when it flakes at a gentle push."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Cajun Fish Tacos','cajun-fish-tacos','seafood','Mexican','https://www.themealdb.com/images/media/meals/uvuyxu1503067369.jpg','themealdb','see themealdb terms',3,15,10,32,490,'{"quick","weeknight"}','{"Rub the fish with cajun spice, oil and salt.","Fry 3 minutes a side in a hot pan until the crust is dark. Do not move it early.","Slaw: shred cabbage and red onion, dress with lime, yoghurt and a pinch of sugar.","Warm the tortillas dry in the pan. Flake the fish in, add slaw, avocado, lime."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Spaghetti alla Carbonara','carbonara','pasta','Italian','https://www.themealdb.com/images/media/meals/llcbn01574260722.jpg','themealdb','see themealdb terms',2,5,15,28,640,'{"quick","weeknight","cheap"}','{"Render the guanciale or pancetta slowly from cold until crisp. Keep the fat.","Beat the eggs with the cheese and a lot of black pepper.","Cook the spaghetti, reserving a mug of water.","Off the heat entirely, toss the pasta with the fat, then the egg mix, loosening with pasta water.","The pan must be off the heat or you get scrambled eggs. No cream, ever."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Chicken and Chorizo Rice Pot','chicken-chorizo-rice','chicken','Spanish','https://www.themealdb.com/images/media/meals/fk80jp1763280767.jpg','themealdb','see themealdb terms',4,10,35,40,650,'{"one-pot","batch","weeknight"}','{"Render the chorizo in a wide pan until the oil runs red. Lift it out.","Brown the chicken in that oil, then set aside with the chorizo.","Soften onion and pepper, add paprika and rice, stir for a minute.","Add stock and tomatoes, return everything, simmer 20 minutes without stirring. Rest 5 minutes off the heat."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Chicken Fried Rice','chicken-fried-rice','chicken','Chinese','https://www.themealdb.com/images/media/meals/wuyd2h1765655837.jpg','themealdb','see themealdb terms',3,10,12,38,540,'{"quick","batch","leftovers"}','{"Use cold rice cooked the day before. Warm rice turns to mush.","Get the wok very hot. Scramble the eggs, remove, set aside.","Fry the chicken hard until coloured, then the aromatics for 30 seconds.","Add the rice and press it into the pan to catch. Toss, add peas and soy.","Return the egg, add spring onions and sesame oil off the heat."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Chicken and Mushroom Hotpot','chicken-mushroom-hotpot','chicken','British','https://www.themealdb.com/images/media/meals/uuuspp1511297945.jpg','themealdb','see themealdb terms',4,20,60,39,590,'{"batch","freezer","comfort"}','{"Brown the chicken thighs in batches. Crowding the pan steams them.","Fry mushrooms hard until they squeak and colour, then onion, garlic and thyme.","Stir in flour, add stock and a splash of milk, bring to a simmer.","Return the chicken, top with sliced potatoes, brush with butter. Bake 50 minutes at 180C until the top is crisp."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Chicken Quinoa Greek Salad','chicken-quinoa-greek','chicken','Greek','https://www.themealdb.com/images/media/meals/k29viq1585565980.jpg','themealdb','see themealdb terms',2,15,20,43,480,'{"high-protein","batch","lunchbox"}','{"Cook the quinoa in stock, drain well and spread out to cool. Wet quinoa ruins the salad.","Season and griddle the chicken, then rest and slice.","Chop cucumber, tomato, red onion and olives. Crumble in feta.","Dress with lemon, olive oil, oregano and pepper. Toss everything through the cooled quinoa."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Chicken Shawarma with Garlic Yoghurt','chicken-shawarma','chicken','Middle Eastern','https://www.themealdb.com/images/media/meals/hcg6l91763596970.jpg','themealdb','see themealdb terms',4,15,25,45,520,'{"high-protein","batch","marinade"}','{"Mix the spices, garlic, lemon juice and half the oil into a paste. Coat the chicken and leave 30 minutes, or overnight if you have it.","Heat the oven to 220C. Spread the chicken on a tray and roast 20-25 minutes until the edges char.","Stir the remaining garlic into the yoghurt with a pinch of salt and a squeeze of lemon.","Rest 5 minutes, slice, and serve in flatbreads with the yoghurt, salad and pickles."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Chickpea Fajitas','chickpea-fajitas','vegetarian','Mexican','https://www.themealdb.com/images/media/meals/tvtxpq1511464705.jpg','themealdb','see themealdb terms',3,10,20,17,450,'{"quick","cheap","vegetarian","weeknight"}','{"Toss peppers and onion in oil, fajita spice and salt. Roast at 220C for 15 minutes.","Drain the chickpeas and pat them dry, then add to the tray for the last 10 minutes so they crisp.","Warm the tortillas dry in a pan.","Serve with yoghurt, lime and avocado. The lime is not optional, it lifts the whole thing."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Chilli Prawn Linguine','chilli-prawn-linguine','pasta','Italian','https://www.themealdb.com/images/media/meals/usywpp1511189717.jpg','themealdb','see themealdb terms',2,5,15,32,560,'{"quick","weeknight","high-protein"}','{"Get the pasta water on and salt it properly. It should taste of the sea.","Gently warm garlic and chilli in olive oil while the linguine cooks.","Add the prawns for 2 minutes, then a ladle of pasta water and the lemon.","Drain the pasta a minute early and finish it in the pan, tossing hard so the starch emulsifies the sauce.","Parsley. No cheese with seafood."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Dal Fry','dal-fry','vegetarian','Indian','https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg','themealdb','see themealdb terms',4,10,35,18,320,'{"batch","freezer","cheap","vegetarian"}','{"Rinse the lentils until the water runs clear, then simmer with turmeric and salt for 25 minutes until collapsing.","Meanwhile heat ghee or oil and fry cumin seeds until they pop.","Add onion, cook to golden, then ginger, garlic and green chilli.","Add tomatoes and ground spices, cook down to a paste.","Stir the tarka through the lentils, loosen with water, finish with coriander and lemon."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Falafel','falafel','vegetarian','Middle Eastern','https://www.themealdb.com/images/media/meals/u5e9qq1763795441.jpg','themealdb','see themealdb terms',4,20,15,19,390,'{"batch","vegetarian","cheap"}','{"Use dried chickpeas soaked overnight, never tinned. Tinned falafel falls apart, and nothing fixes it.","Blitz the drained chickpeas with onion, garlic, parsley, cumin and coriander to a coarse crumb.","Stir in a little flour and baking powder. Rest the mix 30 minutes in the fridge.","Shape into balls and shallow-fry 3 minutes a side until deep brown.","Serve in pitta with tahini sauce, salad and pickled chilli."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Fish Pie','fish-pie','seafood','British','https://www.themealdb.com/images/media/meals/ysxwuq1487323065.jpg','themealdb','see themealdb terms',4,25,40,35,580,'{"batch","freezer","comfort"}','{"Poach the fish in the milk with a bay leaf for 5 minutes. Lift out, keep the milk.","Make a roux with butter and flour, then whisk in the poaching milk to a thick sauce. Add mustard and parsley.","Flake the fish into a dish, add prawns and quartered eggs, pour over the sauce.","Top with mash, rough up the surface with a fork so it crisps, bake 30 minutes at 190C."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Ful Medames','ful-medames','vegetarian','Egyptian','https://www.themealdb.com/images/media/meals/lvn2d51598732465.jpg','themealdb','see themealdb terms',2,5,15,17,330,'{"quick","cheap","breakfast","vegetarian"}','{"Warm the fava beans in their liquid with a crushed garlic clove and cumin for 10 minutes.","Mash roughly with a fork, leaving plenty whole.","Loosen with olive oil and lemon juice until it is spoonable, not stiff.","Top with tomato, parsley, chilli and more oil than feels sensible. Warm flatbread to scoop."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Garlic Prawns with Sherry','garlic-prawns-sherry','seafood','Spanish','https://www.themealdb.com/images/media/meals/u2lhqb1763331899.jpg','themealdb','see themealdb terms',2,5,8,33,340,'{"quick","low-carb","high-protein"}','{"Warm a lot of olive oil gently with sliced garlic and dried chilli. Do not brown the garlic.","When the garlic is pale gold, raise the heat and add the prawns.","Two minutes, turning once, then splash in the sherry and let it bubble away.","Parsley, salt, lemon. Bread to mop the oil is the whole point."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Honey Balsamic Chicken with Broccoli','honey-balsamic-chicken','chicken','American','https://www.themealdb.com/images/media/meals/kvbotn1581012881.jpg','themealdb','see themealdb terms',2,10,35,44,560,'{"one-tray","weeknight","high-protein"}','{"Whisk honey, balsamic, mustard, garlic and oil.","Toss potatoes in half the dressing, roast at 200C for 20 minutes on their own.","Add the chicken and broccoli, pour over the rest, roast 15-18 minutes more.","The broccoli should char at the edges. If it is still soft, give it 5 minutes under the grill."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Honey Teriyaki Salmon','honey-teriyaki-salmon','seafood','Japanese','https://www.themealdb.com/images/media/meals/xxyupu1468262513.jpg','themealdb','see themealdb terms',2,5,15,40,470,'{"quick","high-protein","weeknight"}','{"Mix soy, honey, mirin, grated ginger and garlic.","Sear the salmon skin-side down in a hot dry pan for 4 minutes until the skin releases.","Flip, pour in the sauce, and spoon it over for 3-4 minutes as it thickens.","Do not let the honey catch. Pull the pan off the heat if it darkens fast. Serve with rice and greens."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Jerk Chicken with Rice and Peas','jerk-chicken','chicken','Caribbean','https://www.themealdb.com/images/media/meals/tytyxu1515363282.jpg','themealdb','see themealdb terms',4,20,45,46,620,'{"high-protein","batch","marinade"}','{"Blitz scotch bonnet, spring onion, thyme, allspice, ginger, garlic, soy and lime into a paste.","Score the chicken and rub the paste in. Marinate at least 2 hours, ideally overnight.","Roast at 200C for 40-45 minutes, or barbecue over indirect heat.","For the rice: fry rice in the coconut milk with kidney beans, thyme and a whole scotch bonnet. Simmer covered 20 minutes. Remove the chilli before serving."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Katsu Chicken Curry','katsu-chicken-curry','chicken','Japanese','https://www.themealdb.com/images/media/meals/vwrpps1503068729.jpg','themealdb','see themealdb terms',2,20,30,48,690,'{"high-protein","comfort"}','{"Soften onion, carrot and garlic in oil for 10 minutes. Stir in curry powder and flour, cook 2 minutes.","Add stock gradually, then soy and honey. Simmer 20 minutes and blend smooth.","Flatten the chicken, then flour, egg and panko each piece.","Shallow-fry 4 minutes a side until deep gold. Rest, slice, and pour the sauce alongside rather than over, so the crust stays crisp."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Kedgeree','kedgeree','seafood','British','https://www.themealdb.com/images/media/meals/utxqpt1511639216.jpg','themealdb','see themealdb terms',3,15,25,33,520,'{"batch","breakfast","one-pot"}','{"Poach the smoked haddock in milk 6-8 minutes, then flake, discarding skin and bones.","Soften onion in butter, add curry powder and rice, coat well.","Add stock, simmer covered 12 minutes until the rice is just done.","Fold through the fish, quartered boiled eggs, coriander and lemon. Fold gently or it turns to paste."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Kidney Bean Curry','kidney-bean-curry','vegetarian','Indian','https://www.themealdb.com/images/media/meals/sywrsu1511463066.jpg','themealdb','see themealdb terms',4,10,30,16,340,'{"batch","freezer","cheap","vegetarian"}','{"Fry cumin seeds in oil, then onion until properly browned, not just softened.","Ginger, garlic and green chilli next, then the ground spices for a minute.","Add tomatoes and cook to a thick base.","Add the beans with their liquid and 200ml water, simmer 15 minutes, mashing a few beans to thicken.","Garam masala and coriander at the end, off the heat."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Lamb Kofta Burgers','kofta-burgers','lamb','Middle Eastern','https://www.themealdb.com/images/media/meals/lgmnff1763789847.jpg','themealdb','see themealdb terms',4,15,12,36,540,'{"quick","high-protein","barbecue"}','{"Mix the mince with grated onion, garlic, cumin, coriander, mint and salt.","Shape into flat patties, slightly wider than the bun, and chill 20 minutes.","Fry or grill 5-6 minutes a side. Press once, then leave alone.","Yoghurt with lemon and garlic, tomato, red onion, lettuce, warm bun."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Kung Pao Chicken','kung-pao-chicken','chicken','Chinese','https://www.themealdb.com/images/media/meals/1525872624.jpg','themealdb','see themealdb terms',2,15,10,41,520,'{"quick","high-protein"}','{"Toss the diced chicken in cornflour, soy and rice wine. Leave 10 minutes.","Mix the sauce: soy, vinegar, sugar, stock and a little cornflour.","Very hot wok. Fry dried chillies and Sichuan pepper 20 seconds, then the chicken until coloured.","Add peppers and spring onion, pour in the sauce, toss until glossy. Peanuts last."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Lamb Rogan Josh','lamb-rogan-josh','lamb','Indian','https://www.themealdb.com/images/media/meals/vvstvq1487342592.jpg','themealdb','see themealdb terms',4,20,90,42,610,'{"batch","freezer","slow","high-protein"}','{"Brown the lamb hard in batches and set aside. The colour is the flavour.","Fry onions slowly for 15 minutes until deep gold, then ginger and garlic.","Add the whole spices, then the ground ones, and cook until fragrant.","Stir in yoghurt a spoon at a time off the heat so it does not split.","Return the lamb with a little water, cover, and cook 75-90 minutes until it gives to a spoon."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Lamb and Lemon Souvlaki','lamb-souvlaki','lamb','Greek','https://www.themealdb.com/images/media/meals/rjhf741585564676.jpg','themealdb','see themealdb terms',4,15,15,39,490,'{"high-protein","marinade","barbecue"}','{"Cube the lamb and marinate in lemon, oil, oregano, garlic and pepper for at least 2 hours. Salt just before cooking.","Thread onto skewers, not too tightly, so the heat gets between the pieces.","Grill 12-15 minutes over high heat, turning every few minutes.","Rest 5 minutes. Serve with tzatziki, flatbread, tomato and raw onion."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Lamb Tagine','lamb-tagine','lamb','Moroccan','https://www.themealdb.com/images/media/meals/yuwtuu1511295751.jpg','themealdb','see themealdb terms',4,20,120,41,590,'{"batch","freezer","slow"}','{"Brown the lamb, remove, then soften onion with cinnamon, cumin, coriander and ginger.","Return the lamb with stock, apricots and chickpeas.","Cover and cook very low for 2 hours, or 90 minutes in a 160C oven.","Check the liquid halfway. It should reduce to a gloss, not a soup.","Almonds, coriander and lemon zest at the end. Serve with couscous."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Lancashire Hotpot','lancashire-hotpot','lamb','British','https://www.themealdb.com/images/media/meals/uttrxw1511637813.jpg','themealdb','see themealdb terms',4,25,120,40,620,'{"batch","slow","comfort"}','{"Brown the lamb in batches, then the onions and carrots in the same pan.","Stir in flour, then stock and Worcestershire sauce. Season well.","Layer meat and vegetables in a deep dish, top with overlapping sliced potatoes.","Brush the potatoes with butter, cover, and cook 90 minutes at 160C.","Uncover for the last 30 minutes so the top browns properly."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Smoky Lentil Chilli with Squash','lentil-squash-chilli','vegetarian','American','https://www.themealdb.com/images/media/meals/uwxqwy1483389553.jpg','themealdb','see themealdb terms',4,15,45,20,400,'{"batch","freezer","vegetarian"}','{"Roast the squash cubes with oil and smoked paprika at 200C for 25 minutes.","Meanwhile soften onion and celery, add garlic, cumin and chipotle.","Add lentils, tomatoes and stock, simmer 30 minutes until the lentils are soft.","Fold the roasted squash through at the end so it keeps its shape.","Lime, coriander, yoghurt."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Matar Paneer','matar-paneer','vegetarian','Indian','https://www.themealdb.com/images/media/meals/xxpqsy1511452222.jpg','themealdb','see themealdb terms',3,10,25,24,430,'{"high-protein","vegetarian","one-pot"}','{"Fry the paneer cubes in a little oil until golden on two sides, then lift out.","Soften onion, add ginger, garlic and chilli, then the ground spices.","Add blended tomatoes and cook until the oil separates at the edges. This is the step people skip.","Add peas, water and cream, simmer 8 minutes.","Return the paneer for the last 3 minutes so it stays firm. Coriander to finish."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Pad Thai with Prawns','pad-thai','seafood','Thai','https://www.themealdb.com/images/media/meals/rg9ze01763479093.jpg','themealdb','see themealdb terms',2,15,12,32,610,'{"quick","crowd-pleaser"}','{"Soak the noodles in warm water until pliable but not soft. They finish in the pan.","Mix tamarind, fish sauce and palm sugar. Taste it: sour, salty, sweet, in that order.","Fry garlic, add prawns, push aside and scramble the egg.","Add drained noodles and sauce, toss hard until the noodles take the colour.","Beansprouts and spring onion last. Peanuts, chilli and lime at the table."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Piri-Piri Chicken with Slaw','piri-piri-chicken','chicken','Portuguese','https://www.themealdb.com/images/media/meals/hglsbl1614346998.jpg','themealdb','see themealdb terms',4,15,40,45,540,'{"high-protein","batch","marinade"}','{"Blend red chillies, garlic, smoked paprika, oregano, red wine vinegar, lemon and oil.","Spatchcock the chicken, rub the marinade under and over the skin, leave 2 hours.","Roast at 200C for 40 minutes, basting twice, until the juices run clear.","Slaw: shred cabbage, carrot and onion, dress with lemon, oil and salt. Make it early so it softens."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Prawn Stir-Fry','prawn-stir-fry','seafood','Chinese','https://www.themealdb.com/images/media/meals/96lt871763480970.jpg','themealdb','see themealdb terms',2,10,8,34,380,'{"quick","high-protein","low-carb"}','{"Have everything chopped before you start. This cooks in under ten minutes.","Very hot wok, oil, then ginger and garlic for 20 seconds.","Add the harder vegetables first, then peppers and mangetout.","Prawns last, 2 minutes only. Add soy, oyster sauce and a splash of water, toss and serve."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Salmon Avocado Salad','salmon-avocado-salad','seafood','American','https://www.themealdb.com/images/media/meals/1549542994.jpg','themealdb','see themealdb terms',2,10,10,36,450,'{"quick","low-carb","lunchbox"}','{"Season the salmon and pan-fry 4 minutes a side, or use leftover cooked salmon cold.","Whisk lemon juice, olive oil, mustard and a little honey.","Toss leaves, cucumber, red onion and avocado in most of the dressing.","Flake the salmon over in large pieces rather than stirring it through, so it stays in chunks."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Salmon Noodle Soup','salmon-noodle-soup','seafood','Asian','https://www.themealdb.com/images/media/meals/ikizdm1763760862.jpg','themealdb','see themealdb terms',2,10,15,35,480,'{"quick","one-pot","comfort"}','{"Simmer stock with ginger, garlic, soy and a little miso for 5 minutes.","Add noodles and cook until nearly done.","Lower the salmon in and poach 4-5 minutes until it flakes.","Add greens for the last minute. Finish with lime, chilli oil and coriander."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Sea Bass with Ginger and Chilli','sea-bass-ginger','seafood','Chinese','https://www.themealdb.com/images/media/meals/tqd7s21763780609.jpg','themealdb','see themealdb terms',2,10,12,37,390,'{"quick","low-carb","high-protein"}','{"Score the skin, pat very dry, salt it. Dry skin is crisp skin.","Fry skin-side down in hot oil for 4 minutes, pressing flat. Flip for 1 minute and remove.","In the same pan, sizzle shredded ginger, chilli and spring onion for 30 seconds.","Add soy and a splash of water, pour over the fish. Serve at once with rice and pak choi."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Shakshuka','shakshuka','vegetarian','Middle Eastern','https://www.themealdb.com/images/media/meals/g373701551450225.jpg','themealdb','see themealdb terms',2,10,25,22,410,'{"quick","one-pot","breakfast","vegetarian"}','{"Soften onion and pepper slowly in oil for 10 minutes. Rushing this loses the sweetness.","Add garlic, cumin, paprika and a pinch of chilli, cook 1 minute.","Tip in the tomatoes, season, simmer 12 minutes until thick enough to hold a trough.","Make wells, crack in the eggs, cover and cook 5-7 minutes until the whites set and yolks stay soft.","Feta, parsley, bread."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Sichuan Aubergine','sichuan-aubergine','vegetarian','Chinese','https://www.themealdb.com/images/media/meals/1oz4nb1765687990.jpg','themealdb','see themealdb terms',2,10,20,9,340,'{"vegetarian","cheap","weeknight"}','{"Cut the aubergine into batons and salt them 15 minutes, then pat dry. They soak up less oil that way.","Fry in hot oil until collapsing and browned, then lift out.","Fry chilli bean paste, garlic and ginger for 30 seconds.","Return the aubergine with soy, vinegar, sugar and a splash of water. Simmer until it glazes.","Spring onion on top. Rice underneath."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Spanish Tortilla','spanish-tortilla','vegetarian','Spanish','https://www.themealdb.com/images/media/meals/quuxsx1511476154.jpg','themealdb','see themealdb terms',4,15,30,16,390,'{"batch","cheap","lunchbox","vegetarian"}','{"Slice potatoes thin and cook them gently in plenty of olive oil with the onion for 20 minutes. They should soften, not brown.","Drain, keeping the oil, and season well.","Beat the eggs, stir in the potato and onion, and leave 10 minutes. This is what makes it hold together.","Cook in a smaller pan on a low heat 8 minutes, then invert onto a plate and slide back in for 4 more.","Best eaten warm rather than hot, or cold the next day."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Quinoa and Black Bean Stuffed Peppers','stuffed-peppers-quinoa','vegetarian','Mexican','https://www.themealdb.com/images/media/meals/b66myb1683207208.jpg','themealdb','see themealdb terms',4,15,35,19,410,'{"batch","vegetarian","lunchbox"}','{"Cook the quinoa in stock, 15 minutes, and drain well.","Mix with black beans, sweetcorn, spring onion, cumin, lime and half the cheese.","Halve and deseed the peppers, sit them in a dish, fill generously.","Cover with foil and bake 25 minutes at 190C, then uncover, add the rest of the cheese, 10 minutes more."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Tahini Lentils','tahini-lentils','vegetarian','Middle Eastern','https://www.themealdb.com/images/media/meals/vpxyqt1511464175.jpg','themealdb','see themealdb terms',3,10,30,18,370,'{"batch","cheap","vegetarian","lunchbox"}','{"Simmer puy lentils in stock 25 minutes until tender but still holding shape.","Fry onion slowly until deeply caramelised, at least 15 minutes. This is the flavour.","Whisk tahini with lemon, garlic and cold water until it loosens to a pourable cream.","Fold the onions through the drained lentils, spoon the tahini over, top with parsley and pomegranate."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Tandoori Chicken','tandoori-chicken','chicken','Indian','https://www.themealdb.com/images/media/meals/qptpvt1487339892.jpg','themealdb','see themealdb terms',4,15,30,47,410,'{"high-protein","low-carb","marinade"}','{"Slash the chicken to the bone so the marinade reaches the middle.","Mix yoghurt, ginger, garlic, lemon, garam masala, cumin, chilli and salt. Coat and leave 4 hours minimum.","Heat the oven as high as it goes. Roast on a rack 25-30 minutes, turning once.","Finish under the grill for colour. Serve with lemon, raw onion and mint chutney."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Teriyaki Chicken Casserole','teriyaki-chicken','chicken','Japanese','https://www.themealdb.com/images/media/meals/wvpsxx1468256321.jpg','themealdb','see themealdb terms',4,15,35,44,610,'{"batch","freezer","one-pot"}','{"Simmer soy, mirin, honey, ginger and garlic until it coats a spoon.","Brown the chicken thighs skin-side down, then remove.","Layer rice and vegetables in a dish, sit the chicken on top, pour over the sauce.","Bake covered at 180C for 30 minutes, uncover for 10 more to glaze."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Thai Green Curry','thai-green-curry','chicken','Thai','https://www.themealdb.com/images/media/meals/sstssx1487349585.jpg','themealdb','see themealdb terms',4,10,25,42,480,'{"high-protein","one-pot","freezer"}','{"Fry the curry paste in a splash of the thick coconut cream for 2 minutes until it smells strong.","Add the chicken and turn it in the paste until sealed.","Pour in the rest of the coconut milk and the stock. Simmer 15 minutes.","Add the beans, cook 5 minutes more, then finish with fish sauce, sugar and lime to taste.","Stir through basil off the heat. Serve with jasmine rice."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Thai Prawn Curry','thai-prawn-curry','seafood','Thai','https://www.themealdb.com/images/media/meals/qqlwv91763501559.jpg','themealdb','see themealdb terms',3,10,15,31,440,'{"quick","one-pot","high-protein"}','{"Fry the red curry paste in a little coconut cream until the oil separates.","Add the rest of the coconut milk and stock, simmer 5 minutes.","Add peppers and bamboo shoots, cook 4 minutes.","Prawns go in for the last 2-3 minutes only. Overcooked prawns are rubber. Finish with fish sauce, sugar and lime."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Tofu, Greens and Cashew Stir-Fry','tofu-cashew-stir-fry','vegetarian','Chinese','https://www.themealdb.com/images/media/meals/minfsc1763766806.jpg','themealdb','see themealdb terms',2,15,10,26,480,'{"quick","high-protein","vegetarian"}','{"Press the tofu 20 minutes under something heavy, then cube and toss in cornflour.","Fry in hot oil until crisp on all sides. Move it as little as possible. Lift out.","Toast the cashews in the same pan, then remove.","Garlic, ginger, greens, a splash of water to steam them.","Return tofu and cashews, add soy, rice vinegar and a little sesame oil, toss and serve."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Tuna Nicoise','tuna-nicoise','seafood','French','https://www.themealdb.com/images/media/meals/yypwwq1511304979.jpg','themealdb','see themealdb terms',2,15,15,38,460,'{"lunchbox","low-carb","high-protein"}','{"Boil the new potatoes, adding the green beans for the last 3 minutes. Drain and cool.","Soft-boil the eggs for 7 minutes, then straight into cold water and peel.","Sear the tuna 90 seconds a side and leave it pink in the middle, or use good tinned tuna.","Arrange rather than toss. Dress with olive oil, red wine vinegar, mustard and anchovy."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Vegetarian Chilli','vegetarian-chilli','vegetarian','Mexican','https://www.themealdb.com/images/media/meals/wqurxy1511453156.jpg','themealdb','see themealdb terms',4,15,40,18,380,'{"batch","freezer","cheap","vegetarian"}','{"Soften onion, pepper and carrot for 10 minutes.","Add garlic, cumin, smoked paprika, chipotle and oregano.","Tomatoes, beans, a squeeze of tomato puree and a mug of stock.","Simmer 30 minutes uncovered. It should thicken, not stay soupy.","A square of dark chocolate and a splash of vinegar at the end. Both sound wrong and both work."}'),
('82a17418-cefb-4a9f-8e83-73bebd7838ee','Yaki Udon','yaki-udon','pasta','Japanese','https://www.themealdb.com/images/media/meals/wrustq1511475474.jpg','themealdb','see themealdb terms',2,10,10,18,520,'{"quick","vegetarian","weeknight"}','{"Loosen the udon in hot water and drain. Do not boil them soft.","Very hot pan. Fry cabbage, mushrooms and pepper hard for 3 minutes so they catch.","Add the noodles and let them sit still for a minute to colour.","Pour in soy, mirin and a little oyster or hoisin sauce, toss until glossy.","Spring onion and sesame on top."}')
returning id, slug)
insert into meal_ingredients (meal_id, user_id, item, qty, unit, sort_order)
select m.id, '82a17418-cefb-4a9f-8e83-73bebd7838ee', x.item, x.qty::numeric, x.unit, x.ord
from m join (values
('adana-kebab','lamb mince',700,'g',1),
('adana-kebab','onion',1,null,2),
('adana-kebab','red pepper paste',2,'tbsp',3),
('adana-kebab','Turkish chilli flakes',2,'tsp',4),
('adana-kebab','flatbreads',4,null,5),
('adana-kebab','sumac',1,'tsp',6),
('adana-kebab','red onion',1,null,7),
('arrabbiata-penne','penne',200,'g',1),
('arrabbiata-penne','tinned plum tomatoes',400,'g',2),
('arrabbiata-penne','garlic cloves',4,null,3),
('arrabbiata-penne','dried chilli flakes',1,'tsp',4),
('arrabbiata-penne','olive oil',4,'tbsp',5),
('arrabbiata-penne','parsley',1,'handful',6),
('baked-salmon-fennel','salmon fillets',2,null,1),
('baked-salmon-fennel','fennel bulb',1,null,2),
('baked-salmon-fennel','cherry tomatoes',250,'g',3),
('baked-salmon-fennel','lemon',1,null,4),
('baked-salmon-fennel','olive oil',3,'tbsp',5),
('baked-salmon-fennel','black olives',60,'g',6),
('cajun-fish-tacos','white fish fillets',400,'g',1),
('cajun-fish-tacos','cajun seasoning',2,'tbsp',2),
('cajun-fish-tacos','tortillas',6,null,3),
('cajun-fish-tacos','white cabbage',200,'g',4),
('cajun-fish-tacos','natural yoghurt',100,'g',5),
('cajun-fish-tacos','limes',2,null,6),
('cajun-fish-tacos','avocado',1,null,7),
('carbonara','spaghetti',200,'g',1),
('carbonara','guanciale or pancetta',120,'g',2),
('carbonara','eggs',3,null,3),
('carbonara','pecorino romano',60,'g',4),
('carbonara','black pepper',1,'tsp',5),
('chicken-chorizo-rice','chicken thighs',600,'g',1),
('chicken-chorizo-rice','cooking chorizo',150,'g',2),
('chicken-chorizo-rice','paella or long grain rice',300,'g',3),
('chicken-chorizo-rice','chicken stock',700,'ml',4),
('chicken-chorizo-rice','red pepper',1,null,5),
('chicken-chorizo-rice','onion',1,null,6),
('chicken-chorizo-rice','chopped tomatoes',200,'g',7),
('chicken-chorizo-rice','smoked paprika',2,'tsp',8),
('chicken-fried-rice','cold cooked rice',500,'g',1),
('chicken-fried-rice','chicken breast',300,'g',2),
('chicken-fried-rice','eggs',2,null,3),
('chicken-fried-rice','frozen peas',100,'g',4),
('chicken-fried-rice','garlic cloves',2,null,5),
('chicken-fried-rice','soy sauce',3,'tbsp',6),
('chicken-fried-rice','sesame oil',1,'tsp',7),
('chicken-fried-rice','spring onions',3,null,8),
('chicken-mushroom-hotpot','chicken thighs',800,'g',1),
('chicken-mushroom-hotpot','chestnut mushrooms',300,'g',2),
('chicken-mushroom-hotpot','potatoes',800,'g',3),
('chicken-mushroom-hotpot','onion',1,null,4),
('chicken-mushroom-hotpot','chicken stock',500,'ml',5),
('chicken-mushroom-hotpot','plain flour',2,'tbsp',6),
('chicken-mushroom-hotpot','milk',100,'ml',7),
('chicken-mushroom-hotpot','butter',30,'g',8),
('chicken-mushroom-hotpot','thyme',3,'sprigs',9),
('chicken-quinoa-greek','chicken breasts',2,null,1),
('chicken-quinoa-greek','quinoa',150,'g',2),
('chicken-quinoa-greek','feta',100,'g',3),
('chicken-quinoa-greek','cucumber',1,null,4),
('chicken-quinoa-greek','cherry tomatoes',200,'g',5),
('chicken-quinoa-greek','red onion',1,null,6),
('chicken-quinoa-greek','black olives',80,'g',7),
('chicken-quinoa-greek','lemon',1,null,8),
('chicken-quinoa-greek','dried oregano',1,'tsp',9),
('chicken-shawarma','chicken thighs, boneless',800,'g',1),
('chicken-shawarma','natural yoghurt',200,'g',2),
('chicken-shawarma','garlic cloves',4,null,3),
('chicken-shawarma','ground cumin',2,'tsp',4),
('chicken-shawarma','smoked paprika',2,'tsp',5),
('chicken-shawarma','ground coriander',1,'tsp',6),
('chicken-shawarma','lemon',1,null,7),
('chicken-shawarma','olive oil',3,'tbsp',8),
('chicken-shawarma','flatbreads',4,null,9),
('chickpea-fajitas','chickpeas',400,'g',1),
('chickpea-fajitas','peppers',3,null,2),
('chickpea-fajitas','red onion',1,null,3),
('chickpea-fajitas','fajita seasoning',2,'tbsp',4),
('chickpea-fajitas','tortillas',6,null,5),
('chickpea-fajitas','natural yoghurt',100,'g',6),
('chickpea-fajitas','lime',1,null,7),
('chickpea-fajitas','avocado',1,null,8),
('chilli-prawn-linguine','linguine',200,'g',1),
('chilli-prawn-linguine','raw king prawns',250,'g',2),
('chilli-prawn-linguine','red chilli',1,null,3),
('chilli-prawn-linguine','garlic cloves',3,null,4),
('chilli-prawn-linguine','olive oil',4,'tbsp',5),
('chilli-prawn-linguine','lemon',1,null,6),
('chilli-prawn-linguine','parsley',1,'handful',7),
('dal-fry','red lentils',300,'g',1),
('dal-fry','onion',1,null,2),
('dal-fry','tomatoes',2,null,3),
('dal-fry','ginger',20,'g',4),
('dal-fry','garlic cloves',3,null,5),
('dal-fry','turmeric',1,'tsp',6),
('dal-fry','cumin seeds',1,'tsp',7),
('dal-fry','ghee or oil',2,'tbsp',8),
('dal-fry','coriander',1,'handful',9),
('falafel','dried chickpeas',300,'g',1),
('falafel','onion',1,null,2),
('falafel','garlic cloves',3,null,3),
('falafel','parsley',1,'bunch',4),
('falafel','ground cumin',2,'tsp',5),
('falafel','ground coriander',1,'tsp',6),
('falafel','plain flour',2,'tbsp',7),
('falafel','baking powder',1,'tsp',8),
('falafel','tahini',3,'tbsp',9),
('fish-pie','white fish fillets',500,'g',1),
('fish-pie','smoked haddock',200,'g',2),
('fish-pie','raw prawns',150,'g',3),
('fish-pie','milk',500,'ml',4),
('fish-pie','butter',60,'g',5),
('fish-pie','plain flour',50,'g',6),
('fish-pie','potatoes',1000,'g',7),
('fish-pie','eggs',2,null,8),
('fish-pie','Dijon mustard',1,'tsp',9),
('fish-pie','parsley',1,'handful',10),
('ful-medames','fava beans',400,'g',1),
('ful-medames','garlic clove',1,null,2),
('ful-medames','ground cumin',1,'tsp',3),
('ful-medames','lemon',1,null,4),
('ful-medames','olive oil',3,'tbsp',5),
('ful-medames','tomato',1,null,6),
('ful-medames','parsley',1,'handful',7),
('ful-medames','flatbreads',2,null,8),
('garlic-prawns-sherry','raw king prawns',350,'g',1),
('garlic-prawns-sherry','garlic cloves',6,null,2),
('garlic-prawns-sherry','dried chilli flakes',1,'tsp',3),
('garlic-prawns-sherry','olive oil',100,'ml',4),
('garlic-prawns-sherry','dry sherry',3,'tbsp',5),
('garlic-prawns-sherry','parsley',1,'handful',6),
('garlic-prawns-sherry','crusty bread',1,'loaf',7),
('honey-balsamic-chicken','chicken thighs',600,'g',1),
('honey-balsamic-chicken','new potatoes',600,'g',2),
('honey-balsamic-chicken','broccoli',300,'g',3),
('honey-balsamic-chicken','honey',2,'tbsp',4),
('honey-balsamic-chicken','balsamic vinegar',3,'tbsp',5),
('honey-balsamic-chicken','Dijon mustard',1,'tbsp',6),
('honey-balsamic-chicken','garlic cloves',3,null,7),
('honey-teriyaki-salmon','salmon fillets',2,null,1),
('honey-teriyaki-salmon','soy sauce',3,'tbsp',2),
('honey-teriyaki-salmon','honey',2,'tbsp',3),
('honey-teriyaki-salmon','mirin',2,'tbsp',4),
('honey-teriyaki-salmon','ginger',15,'g',5),
('honey-teriyaki-salmon','garlic clove',1,null,6),
('honey-teriyaki-salmon','rice',150,'g',7),
('jerk-chicken','chicken pieces',1000,'g',1),
('jerk-chicken','scotch bonnet chilli',1,null,2),
('jerk-chicken','spring onions',4,null,3),
('jerk-chicken','ground allspice',2,'tsp',4),
('jerk-chicken','fresh thyme',4,'sprigs',5),
('jerk-chicken','ginger',20,'g',6),
('jerk-chicken','soy sauce',3,'tbsp',7),
('jerk-chicken','long grain rice',300,'g',8),
('jerk-chicken','kidney beans',400,'g',9),
('jerk-chicken','coconut milk',200,'ml',10),
('katsu-chicken-curry','chicken breasts',2,null,1),
('katsu-chicken-curry','panko breadcrumbs',100,'g',2),
('katsu-chicken-curry','egg',1,null,3),
('katsu-chicken-curry','plain flour',50,'g',4),
('katsu-chicken-curry','onion',1,null,5),
('katsu-chicken-curry','carrot',1,null,6),
('katsu-chicken-curry','curry powder',2,'tbsp',7),
('katsu-chicken-curry','chicken stock',400,'ml',8),
('katsu-chicken-curry','honey',1,'tbsp',9),
('kedgeree','smoked haddock',400,'g',1),
('kedgeree','basmati rice',250,'g',2),
('kedgeree','eggs',3,null,3),
('kedgeree','onion',1,null,4),
('kedgeree','curry powder',2,'tsp',5),
('kedgeree','butter',40,'g',6),
('kedgeree','milk',300,'ml',7),
('kedgeree','coriander',1,'handful',8),
('kidney-bean-curry','kidney beans',800,'g',1),
('kidney-bean-curry','onions',2,null,2),
('kidney-bean-curry','chopped tomatoes',400,'g',3),
('kidney-bean-curry','ginger',25,'g',4),
('kidney-bean-curry','garlic cloves',4,null,5),
('kidney-bean-curry','cumin seeds',1,'tsp',6),
('kidney-bean-curry','ground coriander',2,'tsp',7),
('kidney-bean-curry','garam masala',1,'tsp',8),
('kofta-burgers','lamb mince',600,'g',1),
('kofta-burgers','onion',1,null,2),
('kofta-burgers','garlic cloves',2,null,3),
('kofta-burgers','ground cumin',2,'tsp',4),
('kofta-burgers','fresh mint',1,'handful',5),
('kofta-burgers','natural yoghurt',150,'g',6),
('kofta-burgers','burger buns',4,null,7),
('kung-pao-chicken','chicken thighs',400,'g',1),
('kung-pao-chicken','roasted peanuts',60,'g',2),
('kung-pao-chicken','dried red chillies',6,null,3),
('kung-pao-chicken','Sichuan peppercorns',1,'tsp',4),
('kung-pao-chicken','soy sauce',3,'tbsp',5),
('kung-pao-chicken','Chinese black vinegar',2,'tbsp',6),
('kung-pao-chicken','cornflour',2,'tsp',7),
('kung-pao-chicken','spring onions',4,null,8),
('lamb-rogan-josh','lamb shoulder, diced',800,'g',1),
('lamb-rogan-josh','onions',2,null,2),
('lamb-rogan-josh','natural yoghurt',200,'g',3),
('lamb-rogan-josh','ginger',30,'g',4),
('lamb-rogan-josh','garlic cloves',5,null,5),
('lamb-rogan-josh','Kashmiri chilli powder',2,'tsp',6),
('lamb-rogan-josh','ground coriander',2,'tsp',7),
('lamb-rogan-josh','cardamom pods',4,null,8),
('lamb-rogan-josh','cinnamon stick',1,null,9),
('lamb-souvlaki','lamb leg, cubed',700,'g',1),
('lamb-souvlaki','lemons',2,null,2),
('lamb-souvlaki','dried oregano',2,'tsp',3),
('lamb-souvlaki','garlic cloves',4,null,4),
('lamb-souvlaki','olive oil',4,'tbsp',5),
('lamb-souvlaki','natural yoghurt',200,'g',6),
('lamb-souvlaki','cucumber',1,null,7),
('lamb-souvlaki','flatbreads',4,null,8),
('lamb-tagine','lamb shoulder, diced',800,'g',1),
('lamb-tagine','dried apricots',150,'g',2),
('lamb-tagine','chickpeas',400,'g',3),
('lamb-tagine','onion',1,null,4),
('lamb-tagine','ground cumin',2,'tsp',5),
('lamb-tagine','ground cinnamon',1,'tsp',6),
('lamb-tagine','lamb or chicken stock',500,'ml',7),
('lamb-tagine','flaked almonds',50,'g',8),
('lamb-tagine','couscous',250,'g',9),
('lancashire-hotpot','lamb neck or shoulder',800,'g',1),
('lancashire-hotpot','potatoes',1000,'g',2),
('lancashire-hotpot','onions',2,null,3),
('lancashire-hotpot','carrots',2,null,4),
('lancashire-hotpot','lamb stock',500,'ml',5),
('lancashire-hotpot','plain flour',2,'tbsp',6),
('lancashire-hotpot','butter',40,'g',7),
('lancashire-hotpot','Worcestershire sauce',1,'tbsp',8),
('lentil-squash-chilli','butternut squash',600,'g',1),
('lentil-squash-chilli','green lentils',200,'g',2),
('lentil-squash-chilli','chopped tomatoes',400,'g',3),
('lentil-squash-chilli','vegetable stock',600,'ml',4),
('lentil-squash-chilli','onion',1,null,5),
('lentil-squash-chilli','celery sticks',2,null,6),
('lentil-squash-chilli','smoked paprika',2,'tsp',7),
('lentil-squash-chilli','chipotle paste',1,'tbsp',8),
('matar-paneer','paneer',250,'g',1),
('matar-paneer','frozen peas',200,'g',2),
('matar-paneer','tomatoes',3,null,3),
('matar-paneer','onion',1,null,4),
('matar-paneer','ginger',20,'g',5),
('matar-paneer','garam masala',1,'tsp',6),
('matar-paneer','ground coriander',2,'tsp',7),
('matar-paneer','double cream',60,'ml',8),
('pad-thai','flat rice noodles',200,'g',1),
('pad-thai','raw king prawns',250,'g',2),
('pad-thai','eggs',2,null,3),
('pad-thai','tamarind paste',2,'tbsp',4),
('pad-thai','fish sauce',3,'tbsp',5),
('pad-thai','palm or brown sugar',2,'tbsp',6),
('pad-thai','beansprouts',150,'g',7),
('pad-thai','roasted peanuts',50,'g',8),
('pad-thai','lime',1,null,9),
('piri-piri-chicken','whole chicken',1500,'g',1),
('piri-piri-chicken','red chillies',4,null,2),
('piri-piri-chicken','garlic cloves',5,null,3),
('piri-piri-chicken','smoked paprika',2,'tsp',4),
('piri-piri-chicken','red wine vinegar',3,'tbsp',5),
('piri-piri-chicken','olive oil',4,'tbsp',6),
('piri-piri-chicken','white cabbage',300,'g',7),
('piri-piri-chicken','carrot',2,null,8),
('prawn-stir-fry','raw king prawns',300,'g',1),
('prawn-stir-fry','mangetout',150,'g',2),
('prawn-stir-fry','red pepper',1,null,3),
('prawn-stir-fry','ginger',20,'g',4),
('prawn-stir-fry','garlic cloves',2,null,5),
('prawn-stir-fry','soy sauce',2,'tbsp',6),
('prawn-stir-fry','oyster sauce',1,'tbsp',7),
('salmon-avocado-salad','salmon fillets',2,null,1),
('salmon-avocado-salad','avocado',1,null,2),
('salmon-avocado-salad','mixed leaves',100,'g',3),
('salmon-avocado-salad','cucumber',1,null,4),
('salmon-avocado-salad','red onion',1,null,5),
('salmon-avocado-salad','lemon',1,null,6),
('salmon-avocado-salad','Dijon mustard',1,'tsp',7),
('salmon-noodle-soup','salmon fillets',2,null,1),
('salmon-noodle-soup','fish or chicken stock',800,'ml',2),
('salmon-noodle-soup','egg noodles',150,'g',3),
('salmon-noodle-soup','miso paste',1,'tbsp',4),
('salmon-noodle-soup','ginger',20,'g',5),
('salmon-noodle-soup','pak choi',150,'g',6),
('salmon-noodle-soup','lime',1,null,7),
('sea-bass-ginger','sea bass fillets',2,null,1),
('sea-bass-ginger','ginger',30,'g',2),
('sea-bass-ginger','red chilli',1,null,3),
('sea-bass-ginger','spring onions',3,null,4),
('sea-bass-ginger','soy sauce',2,'tbsp',5),
('sea-bass-ginger','pak choi',200,'g',6),
('shakshuka','eggs',4,null,1),
('shakshuka','chopped tomatoes',400,'g',2),
('shakshuka','red pepper',1,null,3),
('shakshuka','onion',1,null,4),
('shakshuka','garlic cloves',3,null,5),
('shakshuka','ground cumin',1,'tsp',6),
('shakshuka','smoked paprika',1,'tsp',7),
('shakshuka','feta',80,'g',8),
('sichuan-aubergine','aubergines',2,null,1),
('sichuan-aubergine','chilli bean paste',2,'tbsp',2),
('sichuan-aubergine','garlic cloves',3,null,3),
('sichuan-aubergine','ginger',20,'g',4),
('sichuan-aubergine','soy sauce',2,'tbsp',5),
('sichuan-aubergine','Chinese black vinegar',1,'tbsp',6),
('sichuan-aubergine','spring onions',2,null,7),
('spanish-tortilla','eggs',6,null,1),
('spanish-tortilla','potatoes',600,'g',2),
('spanish-tortilla','onion',1,null,3),
('spanish-tortilla','olive oil',200,'ml',4),
('stuffed-peppers-quinoa','peppers',4,null,1),
('stuffed-peppers-quinoa','quinoa',200,'g',2),
('stuffed-peppers-quinoa','black beans',400,'g',3),
('stuffed-peppers-quinoa','sweetcorn',200,'g',4),
('stuffed-peppers-quinoa','cheddar',100,'g',5),
('stuffed-peppers-quinoa','ground cumin',2,'tsp',6),
('stuffed-peppers-quinoa','lime',1,null,7),
('tahini-lentils','puy lentils',250,'g',1),
('tahini-lentils','onions',2,null,2),
('tahini-lentils','tahini',4,'tbsp',3),
('tahini-lentils','lemon',1,null,4),
('tahini-lentils','garlic clove',1,null,5),
('tahini-lentils','parsley',1,'handful',6),
('tahini-lentils','pomegranate seeds',60,'g',7),
('tandoori-chicken','chicken legs',8,null,1),
('tandoori-chicken','natural yoghurt',250,'g',2),
('tandoori-chicken','ginger',30,'g',3),
('tandoori-chicken','garlic cloves',5,null,4),
('tandoori-chicken','garam masala',2,'tsp',5),
('tandoori-chicken','ground cumin',2,'tsp',6),
('tandoori-chicken','chilli powder',1,'tsp',7),
('tandoori-chicken','lemon',1,null,8),
('teriyaki-chicken','chicken thighs',700,'g',1),
('teriyaki-chicken','soy sauce',100,'ml',2),
('teriyaki-chicken','mirin',60,'ml',3),
('teriyaki-chicken','honey',3,'tbsp',4),
('teriyaki-chicken','ginger',25,'g',5),
('teriyaki-chicken','rice',300,'g',6),
('teriyaki-chicken','broccoli',250,'g',7),
('teriyaki-chicken','carrots',2,null,8),
('thai-green-curry','chicken thighs',600,'g',1),
('thai-green-curry','green curry paste',3,'tbsp',2),
('thai-green-curry','coconut milk',400,'ml',3),
('thai-green-curry','chicken stock',150,'ml',4),
('thai-green-curry','green beans',150,'g',5),
('thai-green-curry','fish sauce',2,'tbsp',6),
('thai-green-curry','palm or brown sugar',1,'tsp',7),
('thai-green-curry','Thai basil',1,'handful',8),
('thai-green-curry','lime',1,null,9),
('thai-prawn-curry','raw king prawns',400,'g',1),
('thai-prawn-curry','red curry paste',3,'tbsp',2),
('thai-prawn-curry','coconut milk',400,'ml',3),
('thai-prawn-curry','red pepper',1,null,4),
('thai-prawn-curry','bamboo shoots',150,'g',5),
('thai-prawn-curry','fish sauce',2,'tbsp',6),
('thai-prawn-curry','lime',1,null,7),
('tofu-cashew-stir-fry','firm tofu',400,'g',1),
('tofu-cashew-stir-fry','cashew nuts',80,'g',2),
('tofu-cashew-stir-fry','tenderstem broccoli',200,'g',3),
('tofu-cashew-stir-fry','pak choi',150,'g',4),
('tofu-cashew-stir-fry','cornflour',3,'tbsp',5),
('tofu-cashew-stir-fry','soy sauce',3,'tbsp',6),
('tofu-cashew-stir-fry','rice vinegar',1,'tbsp',7),
('tofu-cashew-stir-fry','ginger',20,'g',8),
('tuna-nicoise','tuna steaks',2,null,1),
('tuna-nicoise','new potatoes',300,'g',2),
('tuna-nicoise','green beans',150,'g',3),
('tuna-nicoise','eggs',2,null,4),
('tuna-nicoise','black olives',60,'g',5),
('tuna-nicoise','anchovy fillets',4,null,6),
('tuna-nicoise','red wine vinegar',2,'tbsp',7),
('tuna-nicoise','olive oil',4,'tbsp',8),
('vegetarian-chilli','black beans',400,'g',1),
('vegetarian-chilli','kidney beans',400,'g',2),
('vegetarian-chilli','chopped tomatoes',400,'g',3),
('vegetarian-chilli','onion',1,null,4),
('vegetarian-chilli','red pepper',1,null,5),
('vegetarian-chilli','carrot',1,null,6),
('vegetarian-chilli','chipotle paste',1,'tbsp',7),
('vegetarian-chilli','smoked paprika',2,'tsp',8),
('vegetarian-chilli','dark chocolate',10,'g',9),
('yaki-udon','udon noodles',400,'g',1),
('yaki-udon','white cabbage',200,'g',2),
('yaki-udon','shiitake mushrooms',150,'g',3),
('yaki-udon','red pepper',1,null,4),
('yaki-udon','soy sauce',3,'tbsp',5),
('yaki-udon','mirin',2,'tbsp',6),
('yaki-udon','spring onions',3,null,7)
) as x(slug, item, qty, unit, ord) on x.slug = m.slug;
